# Generated by Django 5.2.1 on 2025-05-31 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="cfms.type",
                verbose_name="Тип",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Название категории"),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "type")},
        ),
    ]
