# Generated by Django 5.2.1 on 2025-05-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfms", "0002_category_type_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=64, unique=True, verbose_name="Название статуса"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Название подкатегории"),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(max_length=64, unique=True, verbose_name="Название типа"),
        ),
    ]
